# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Karaoke' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Karaoke
  pod 'SnapKit', '~> 4.0.0'
  pod 'SwipeCellKit'

  target 'KaraokeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KaraokeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
